# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\CreateRouteWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import Route_confirmation
from main_menu import Ui_MainWindow
from Route_confirmation import Ui_RouteRecap

from main import User
import utils
checkboxes = []


class Ui_CreateRouteWindow(object):
    def back_btn(self):
        # go back to main window
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def show_dialog(self, info):
        self.dialog = QtWidgets.QDialog()
        self.ui = Ui_RouteRecap()
        self.ui.setupUi(self.dialog, info)
        self.dialog.show()

    def get_data(self):
        route_data = [self.checkbox_data(), self.slider_data(), self.radio_data(), self.combo_data(), self.date_data()]
        print("ROUTE", route_data)
        #create json file with route data

        print(route_data)
        with open("route_data.txt", "w") as f:
            for item in route_data:
                for i in item:
                    f.write(str(i) + "\n")
                f.write("\n")
        return route_data

    def checkbox_data(self):
        selected_activities = []
        for i in range(len(checkboxes)):
            print("checkboxes[i]: ", checkboxes[i].isChecked())
        for i in range(len(utils.activities)):
            if checkboxes[i].isChecked():
                selected_activities.append(utils.activities[i])
        return selected_activities

    #get data from slider
    def slider_data(self):
        severity = [self.severity_level.value()]
        return severity

    #get data from radio buttons
    def radio_data(self):
        radio_data = ["Not stated", "Not stated"]
        if self.radioButton.isChecked():
            radio_data[0] = self.radioButton.text()
        if self.radioButton_2.isChecked():
            radio_data[0] = self.radioButton_2.text()
        if self.radioButton_3.isChecked():
            radio_data[1] = self.radioButton_3.text()
        if self.radioButton_4.isChecked():
            radio_data[1] = self.radioButton_4.text()
        return radio_data

    #get data from combo boxes
    def combo_data(self):
        location = []
        location.append(self.start_location_combo.currentText())
        location.append(self.end_location_combo.currentText())
        return location

    #get data from dateEdit
    def date_data(self):
        date = [self.dateEdit.text()]
        return date

    def setupUi(self, CreateRouteWindow):
        CreateRouteWindow.setObjectName("CreateRouteWindow")
        CreateRouteWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(CreateRouteWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(270, 20, 256, 51))
        self.textBrowser.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser.setObjectName("textBrowser")
        self.severity_level = QtWidgets.QSlider(self.centralwidget)
        self.severity_level.setGeometry(QtCore.QRect(400, 220, 211, 31))
        self.severity_level.setMaximum(10)
        self.severity_level.setPageStep(1)
        self.severity_level.setSliderPosition(5)
        self.severity_level.setTracking(True)
        self.severity_level.setOrientation(QtCore.Qt.Horizontal)
        self.severity_level.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.severity_level.setTickInterval(1)
        self.severity_level.setObjectName("severity_level")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(30, 140, 131, 31))
        self.textBrowser_2.setAutoFillBackground(True)
        self.textBrowser_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_3.setGeometry(QtCore.QRect(30, 180, 121, 31))
        self.textBrowser_3.setAutoFillBackground(True)
        self.textBrowser_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_4.setGeometry(QtCore.QRect(430, 190, 151, 31))
        self.textBrowser_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_4.setObjectName("textBrowser_4")

        self.create_route_btn = QtWidgets.QPushButton(self.centralwidget)
        self.create_route_btn.setGeometry(QtCore.QRect(510, 490, 241, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.create_route_btn.setFont(font)
        self.create_route_btn.setObjectName("create_routebtn")

        self.create_route_btn.clicked.connect(self.get_data)
        # show dialog window on click and pass summary data

        #self.create_route_btn.clicked.connect(lambda: self.show_dialog(self.get_data()))
        self.create_route_btn.clicked.connect(CreateRouteWindow.close)

        self.create_route_btn.clicked.connect(utils.route.create_route)

        #self.create_route_btn.clicked.connect(lambda: utils.user.create_group(self.get_data()))

        self.textBrowser_5 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_5.setGeometry(QtCore.QRect(390, 140, 151, 31))
        self.textBrowser_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(470, 140, 141, 31))
        self.dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2022, 12, 15), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setObjectName("dateEdit")

        self.activities_checkbox()
        self.combobox_end()
        self.combobox_start()

        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(380, 280, 341, 161))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_2.setGeometry(QtCore.QRect(170, 60, 151, 91))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_3.setGeometry(QtCore.QRect(20, 20, 101, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_4.setGeometry(QtCore.QRect(20, 50, 111, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_4.setFont(font)
        self.radioButton_4.setObjectName("radioButton_4")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox.setGeometry(QtCore.QRect(10, 60, 151, 91))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setGeometry(QtCore.QRect(20, 20, 101, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setGeometry(QtCore.QRect(20, 50, 111, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.textBrowser_7 = QtWidgets.QTextBrowser(self.groupBox_3)
        self.textBrowser_7.setGeometry(QtCore.QRect(10, 20, 151, 31))
        self.textBrowser_7.setAutoFillBackground(True)
        self.textBrowser_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_7.setObjectName("textBrowser_7")

        self.textBrowser_6 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_6.setGeometry(QtCore.QRect(30, 240, 121, 31))
        self.textBrowser_6.setAutoFillBackground(True)
        self.textBrowser_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_6.setObjectName("textBrowser_6")

        CreateRouteWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(CreateRouteWindow)
        self.statusbar.setObjectName("statusbar")
        CreateRouteWindow.setStatusBar(self.statusbar)

        self.menubar = QtWidgets.QMenuBar(CreateRouteWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        CreateRouteWindow.setMenuBar(self.menubar)

        self.Backbtn = QtWidgets.QPushButton(self.centralwidget)
        self.Backbtn.setGeometry(QtCore.QRect(20, 490, 241, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Backbtn.setFont(font)
        self.Backbtn.setObjectName("Backbtn")
        self.Backbtn.clicked.connect(self.back_btn)
        self.Backbtn.clicked.connect(CreateRouteWindow.close)

        self.retranslateUi(CreateRouteWindow)
        QtCore.QMetaObject.connectSlotsByName(CreateRouteWindow)

    def activities_checkbox(self):

        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(30, 290, 140, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 100))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 121, 186))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")

        checkboxes.clear()

        for i in range(len(utils.activities)):
            checkboxes.append(QtWidgets.QCheckBox(self.scrollAreaWidgetContents))
            checkboxes[i].setText(utils.activities[i])
            self.verticalLayout.addWidget(checkboxes[i])

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

    def combobox_start(self):
        self.start_location_combo = QtWidgets.QComboBox(self.centralwidget)
        self.start_location_combo.setGeometry(QtCore.QRect(190, 140, 151, 31))
        self.start_location_combo.setCurrentText("Select start location")
        self.start_location_combo.setObjectName("start_location_combo")

        self.start_location_combo.addItems(utils.start_location_list)

    def combobox_end(self):
        self.end_location_combo = QtWidgets.QComboBox(self.centralwidget)
        self.end_location_combo.setGeometry(QtCore.QRect(190, 180, 151, 31))
        self.end_location_combo.setCurrentText("Select end location")
        self.end_location_combo.setObjectName("end_location_combo")

        self.end_location_combo.addItems(utils.end_location_list)

    def retranslateUi(self, CreateRouteWindow):
        _translate = QtCore.QCoreApplication.translate
        CreateRouteWindow.setWindowTitle(_translate("CreateRouteWindow", "CreateRouteWindow"))
        self.radioButton_3.setText(_translate("CreateRouteWindow", "Camp"))
        self.radioButton_4.setText(_translate("CreateRouteWindow", "Hotel"))
        self.radioButton.setText(_translate("CreateRouteWindow", "Alone"))
        self.radioButton_2.setText(_translate("CreateRouteWindow", "Group"))
        self.Backbtn.setText(_translate("CreateRouteWindow", "Back"))
        self.textBrowser_7.setHtml(_translate("CreateRouteWindow",
                                              "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                              "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                              "p, li { white-space: pre-wrap; }\n"
                                              "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                              "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Travel options:</span></p></body></html>"))

        self.textBrowser.setHtml(_translate("CreateRouteWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt; font-weight:600;\">Create Route</span></p></body></html>"))
        self.textBrowser_2.setHtml(_translate("CreateRouteWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Start location:</span></p></body></html>"))
        self.textBrowser_3.setHtml(_translate("CreateRouteWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">End location:</span></p></body></html>"))
        self.textBrowser_4.setHtml(_translate("CreateRouteWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Route severity:</span></p></body></html>"))
        self.create_route_btn.setText(_translate("CreateRouteWindow", "Create route"))
        self.textBrowser_5.setHtml(_translate("CreateRouteWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Date:</span></p></body></html>"))
        self.textBrowser_6.setHtml(_translate("CreateRouteWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Activities:</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CreateRouteWindow = QtWidgets.QMainWindow()
    ui = Ui_CreateRouteWindow()
    ui.setupUi(CreateRouteWindow)
    CreateRouteWindow.show()
    sys.exit(app.exec_())
